### ISSUE TITLE
Tutorial for installing whook on an Amazon EC2 Linux virtual machine

### ISSUE THREAD

**Issue by iZnogoude** [germangar/whook#11]
Hello there,

I created a tutorial in order to use ubuntu with AWS virtual machine. Much better than windows for this purpose !
You will find it on the fork I created of this project on my github.

If you need it by email, just ask.

Please don't hesitate to give me some feedback about it, because maby some process could be replaced by a better one, like noip.com for instance.

**Comment by germangar** [comment]
Thank you! I added it to the repository.
