### ISSUE TITLE
Coinex futures error

### ISSUE THREAD

**Issue by mtrade0** [germangar/whook#12]
Hello and thank your hard work in creating this. I'm able to get everything up and running just fine, yet when trading view sends an alert to the server I get the following response:

_"* E: Couldn't reach the server: Cancelling 'list' object has no attribute 'get' <class 'AttributeError'>"_

I've tried my best to figure out on my own, but I'm not familiar with flask.

**Comment by germangar** [comment]
Hey,
I just comitted a fix. Update and it should be working now.

**Comment by mtrade0** [comment]
Is working now! thanks!
