### ISSUE TITLE
Unhandled exception, error with bitget

### ISSUE THREAD

**Issue by iZnogoude** [germangar/whook#13]
Hello there,

I tried to make some news tests in one-side mode with bitget exange, my whook seems to reach correctly bitget server, but when an order is initiated by my bot, I have this error. I'm struggling since a couple of days and everything was the same when I was using bingx.

`[2024/06/07][09:30:02]  ALERT: iznogoude31@gmail.com NOT/USDT:USDT buy 2710.644@ x3
[2024/06/07][09:30:02] ----------------------------
[2024/06/07][09:30:04]  * E: Unhandled exception. Cancelling: bitget {"code":"400172","msg":"side mismatch","requestTime":1717752604241,"data":null} <class 'ccxt.base.errors.ExchangeError'>  updateOrdersQueue`

Do you have any idea that could help me please?

**Comment by germangar** [comment]
I think if you make your order in contracts you can't use fractional numbers. I guess I never thought to add a check in the code for this. I will verify this is the reason for the error and add it.

Try making the same order in the coin (NOT in this case) and see if that fixes it.

**Comment by germangar** [comment]
Yes. CCXT had changed their Bitget code. I updated whook and it's working now.

Today I closed the positions in Bingx so tomorrow I'll try to figure out what was going on with it.

**Comment by iZnogoude** [comment]
Hello !
It works !
But, the margin mode was not good, I have set up crossed in the accounts.json and the position was taken in isolated.
In the exchange it was set up on isolated, so I suppose that the error comes from here, even if my order should be in crossed and not isolated margin mode.

```
[2024/06/08][12:45:01]  ALERT: BGUSER-1M3ZWDAW ONDO/USDT:USDT buy 58.8@ x3
[2024/06/08][12:45:01] ----------------------------
[2024/06/08][12:45:03]  * Order successful: ONDO/USDT:USDT buy 58.8 3x at price 1.303 id 1183317101616209920
```

I thought the margin mode should appears in the log also?

I ran a news test to see if the one-side mode is working better also.

**Comment by germangar** [comment]
Didn't it print the position right after the order? The margin mode appears in there

I didn't pay attention to the leverage being correct. I'll check it now.

**Comment by iZnogoude** [comment]
No, the position taken was leverage 4 in the exchange and not 3. I change it manually on the exchange, and now it seems to work ok.
Maybe you could check the leverage on bitget in your code?

Thanks to be so fast !!!!

**Comment by germangar** [comment]
I'm testing the leverage but it's working fine for me. I set it in the website to 7x before making an order with 3x and the position opened was at 3x

```
17:27:32 [bitget/bitget]  
17:27:32 [bitget/bitget]  ALERT: bitget LDOUSDT pos 5$ x3
17:27:32 [bitget/bitget] ----------------------------    
17:27:37 [bitget/bitget]  * Order successful: LDO/USDT:USDT buy 7.6 3x at price 1.9622 id 1183358015332057091
------------------------------
  1 positions found.
  LDO/USDT:USDT * isolated:3x * long * 7.6 * 4.9709[$] * -0.02[$] * -0.31%
```

![image](https://github.com/germangar/whook/assets/83035204/17782259-b505-4e77-9226-e01ecf293669)

**Comment by iZnogoude** [comment]
I have to do additional tests on this issue, but I'm strugging on the other issue ;S
This is not a major issue of course, but when I will launch my bot again I will keep you updated.
