### ISSUE TITLE
Could u add features use percentage of available balance and add password protection to account_id?

### ISSUE THREAD

**Issue by mvthul** [germangar/whook#2]
Lets say risk 5% of available balance in account.

Password protect webhook post message like account_id + password ETH/USDT buy 500$ x125

**Comment by germangar** [comment]
Yes. I was planning to add orders by percentage of balance. I'll do it one of these days.

I'm not sure what security value would add having a password in the alert. Both the account name and the alert would be in the same place. If someone finds one he would also find the other. Or am I missing something?

It's not hard to add at all. I just don't figure out the situation where it would be really needed.

**Comment by mvthul** [comment]
Leave the password question I noticed setting up a account is with 14 + characters should be safe enough. 7tRtilcaC85Is5335B almost uncrackable!

looking forward to the balance order type

**Comment by germangar** [comment]
Orders by percentage of balance are up.

**Comment by mvthul** [comment]
Sweet I’m gonna make a docker image for this. So I can scale this with Kubernetes and loadbalance it properly!
