### ISSUE TITLE
Requesting Exchanges (info)

### ISSUE THREAD

**Issue by germangar** [germangar/whook#5]
Adding new exchanges is a pretty simple proccess at this point. I will accept requests, but some conditions need to be met.

- The exchange needs to be supported by ccxt.
- If the exchange has a testnet I'll straight up give it a try.
- If the exchange doesn't have a testnet I'll ask the person requesting it to create a subaccount, move 15USDT there and share the subaccount API keys with me (privately! trading permission only). I'll probably spend 2 or 3 USDT in trading fees during the implementation. Once it's done the subaccount can be deleted.

Note: I will not add Mexc. I already did, only to find out the exchange doesn't allow to place orders since 2022.

**Comment by a202037** [comment]
Hi, thanks for the development and it's a very nice repo. Is that possible to add support to krakenfutues ?

**Comment by germangar** [comment]
Hi,
I was able to create API Keys at demo-futures.kraken.com and connect to it. There is a problem, tho. I don't find any trading pairs with USDT in the site, and all my code asumes trading using USDT. I'll see if I can work around it, but I can't promise success.

**Comment by germangar** [comment]
Kraken futures support added.

It has a couple of weaknesses compared to all the other exchanges, tho. Kraken doesn't offer a way to modify the margin mode from the API, so Whook won't set the margin to isolated as it does for every other exchange. The user needs to go to the website and change it himself (when going to trade a new coin).

It also doesn't report the margin mode correctly when printing the positions in the console. It always prints isolated because it doesn't know what's the margin mode in the server.

And last. Kraken doesn't either report the maximum leverage accepted for each symbol, so you have to careful not to exceed it or the order won't go through.

Other than these, it's working fine. Market and limit orders and going through just fine.

PS: I only tested it in the testnet server. I don't have account on the real server. Kraken (as Binance) has futures blocked in my country.

**Comment by maddrid** [comment]
hi @germangar  i  can    provide  some  bingx   subaccount  api
  could  you send    me some    details  how  to contact you

**Comment by germangar** [comment]
Hey, thank you! You can send me an email to germangarciaart(AT)gmail.com

**Comment by AlexanderWatersOxygen** [comment]
First off all thanks!!! Got it to work on kucoin, but on bybit it gives an error. So it seems to reocognize two open posititions
but trading doesn't work. Have you had this problem before and do you know how to solve it?


23:13:29  Initializing account: [ BYBIT__AlexW_G_main ] in [ bybit ]
------------------------------
  2 positions found.
 * W: refreshPositions: Could not get marginMode for ARB/USDT:USDT
 * W: refreshPositions: Could not get marginMode for ETC/USDT:USDT
Account creation failed: can only concatenate str (not "NoneType") to str <class 'TypeError'>
------------------------------
 Warm regards,

Alexander

**Comment by germangar** [comment]
Hello. I haven't used Bybit in quite a while. Probably something has changed in either ccxt or the exchange that has triggered a bug. I'll take a look into it in the next few days.

**Comment by germangar** [comment]
@AlexanderWatersOxygen It's fixed in the repository.

**Comment by AlexanderWatersOxygen** [comment]
> @AlexanderWatersOxygen I committed a quick fix. Update and it should work fine.

that is amazing!! Thanks

**Comment by AlexanderWatersOxygen** [comment]
the error is above is resolved, but i encountered a one with placing orders.
So the first part; reading the account info works

19:26:31  Initializing account: [ BYBIT__AlexW_G_main ] in [ bybit ]
------------------------------
  1 positions found.
  BTC/USDT:USDT * cross:10x * short * 0.012 * 84.7642[$] * -0.08[$] * -0.09%

but when placing an order it says (i tried a few ways of webhook styles):

19:15:02  * E: Account ID not found. ALERT: BYBIT__AlexW_G_main btc/USDT:USDT 10$ buy 10x
19:30:44  * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etc/USDT:USDT 100$ short 10x
19:31:21  * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etc/USDT 100$ short 10x
19:35:46  * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etcUSDT 100$ short 10x

ps feel a little bit bad to ask you again, but to get to your level of understanding the matter will take me few more years haha

**Comment by germangar** [comment]
No, no. Don't feel bad. Please report these things. I don't use Bybit anymore and, while I try to check from time to time in a demo account, things in ccxt and the exchange always keep changing and my code may get a little outdated.

However, I tried placing and closing an order when I did the other fix and it was working for me. Is your ccxt version current?

I'll try to reproduce it and fix it when I have a moment.

**Comment by germangar** [comment]
Oh. One thing. The symbol name must be all caps (That's one thing I can improve in the code)

```
21:26:54 [bybitdemo/bybit]
21:26:54 [bybitdemo/bybit]  ALERT: btc/USDT:USDT bybitdemo pos 10$ 10x
21:26:54 [bybitdemo/bybit] ----------------------------
21:26:54 [bybitdemo/bybit]  * E: Couldn't find symbol
```

**Comment by germangar** [comment]
> the error is above is resolved, but i encountered a one with placing orders. So the first part; reading the account info works
> 
> ## 19:26:31 Initializing account: [ BYBIT__AlexW_G_main ] in [ bybit ]
> 1 positions found. BTC/USDT:USDT * cross:10x * short * 0.012 * 84.7642[$] * -0.08[$] * -0.09%
> 
> but when placing an order it says (i tried a few ways of webhook styles):
> 
> 19:15:02 * E: Account ID not found. ALERT: BYBIT__AlexW_G_main btc/USDT:USDT 10$ buy 10x 19:30:44 * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etc/USDT:USDT 100$ short 10x 19:31:21 * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etc/USDT 100$ short 10x 19:35:46 * E: Account ID not found. ALERT: BYBIT__AlexW_G_main etcUSDT 100$ short 10x
> 


Hold on. I notice your position is in cross margin mode. Did you open that position from the website or is your account setup for cross margin?
Can you check if the position in the website/app is showing as cross margin too?

**Comment by AlexanderWatersOxygen** [comment]
It worked. it was indeed the CCXT update!  Many thanks for your assistance!
I opened indeed the position manually from the website to see if the positions where read ok. 

It really works great. Really great job!!!

**Comment by AlexanderWatersOxygen** [comment]
After your last message I will take the liberty to request/ ask you something:

When placing a limit order is; is it possible to make it a 'Post Only' (or is that already the case?) because with a _maker order _ you could get super low fees :) of course with the risk orders don't get filled. :)

btw (as a side note. When you place a long order that balances out a short order and vise versa, you don't pay funding fees on a few exchanges i tested).
anyway the less fees the more likely a bot is profitable (if orders get filled of course :P) !!!!

**Comment by germangar** [comment]
I'm afraid only a few exchanges offer that possibility from the API. I checked Bybit documentation and I don't see how to do it.

If you use limit orders you will be a maker, but I think if the order is instantly triggered (the price was already in the range) it's not considered a maker, and that's where postOnly would make a difference.

I had the plan to make a special market order that would place the order as limit order checking the most recent price and using it, but it's a risky thing to use if the price is trending hard. I imagine only a percentage of orders would enter as maker, but it's better than nothing.

**Comment by AlexanderWatersOxygen** [comment]
> I'm afraid only a few exchanges offer that possibility from the API. I checked Bybit documentation and I don't see how to do it.
> 
> If you use limit orders you will be a maker, but I think if the order is instantly triggered (the price was already in the range) it's not considered a maker, and that's where postOnly would make a difference.
> 
> I had the plan to make a special market order that would place the order as limit order checking the most recent price and using it, but it's a risky thing to use if the price is trending hard. I imagine only a percentage of orders would enter as maker, but it's better than nothing.

Ok thanks for looking into it, and your answer! 
I didn't know that distinction of the price being in the range... but makes sense.

Yeah I reckoned that the might be problematic with trending markets and or ad hoc orders (that many bots have). 

Already get an headache thinking about the complexity of programming, when having for example, a check if orders were filled, so that when you would place a opposite order (to avoid the funding fees), you don't end up shorting or longing a position that you wanted neutralized/ paid out, because a order was not (or not completely) filled. Anyways, a close order would always work :D

And contemplating on it, I guess that placing postOnly orders makes most sense when let's say you want to make predetermined exits or entries at for example support and resistance levels. But then you still would have to put in a trigger price and actual limit order price to be most sure they get filled right?

**Comment by techsnakebo** [comment]
hi, it works great, I'm testing it with bingX

But I have a doubt

Can an AccountID serve as a position identifier? For example, if I have a long position in ETHUSDT using accountID1 on the same exchange, and then open a short position in ETHUSDT with accountID2, can the program differentiate these trades based on the accountID? In other words, if I later send a close command to the trade with accountID1, will it only close that specific trade or will it close all open trades corresponding to the same coin pair at that moment on the same exchange?

thanks
