### ISSUE TITLE
Undefined positionContracts in parseAlert

### ISSUE THREAD

**Issue by maddrid** [germangar/whook#6]
line 1419, in parseAlert
    command = 'sell' if positionContracts > quantity else 'buy'
TypeError: '>' not supported between instances of 'NoneType' and 'float'
 command = 'sell' if positionContracts > quantity else 'buy'

**Comment by germangar** [comment]
Hey, thank you for the report. Could you tell me what exchange was it on? Also, did this happen with a recent revision? I'll do my best to fix it asap and I have a close idea of what happened, but it would help a lot if I could reproduce it.
