### ISSUE TITLE
Leverage limits

### ISSUE THREAD

**Issue by iZnogoude** [germangar/whook#9]
@germangar 
Hello ! Sorry to have put my issue on the CCXT project. I'm a noob using github. '^_^
in fact I did just the update of my whook aws server yesterday with a friend (because I'm also a noob with Python). My friend did a fork of your project and it seems that you have used his code. I'm really happy about that :)
I'm testing the leverage limit in isolated mode for the moment.
I will test soon in cross mode and I will give you backup as soon as tested.

My friend ask if its possible to have more parameters out of the main.py transferred to the accounts.json like
- proxy mode
- ports numbers

It would be great :)

Moreover, I have a very good tutorial in order to build a whook server hosted in AWS but on linux based. It's in french, but I could translate it an give it to you if you want.

**Comment by germangar** [comment]
That's definitely wrong. STX has up to 50x leverage in isolated. I'll hunt the bug down.

**Comment by germangar** [comment]
I'm afraid this is a bug in BINGX. The information it's sending through the API states the maximum leverage for STX is 5x.

```
{'active': True,
 'base': 'STX',
 'baseId': 'STX',
 'contract': True,
 'contractSize': 1.0,
 'created': None,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'quote',
 'future': False,
 'id': 'STX-USDT',
 'index': None,
 'info': {'apiStateClose': 'true',
          'apiStateOpen': 'true',
          'asset': 'STX',
          'contractId': '100196',
          'currency': 'USDT',
          'ensureTrigger': True,
          'feeRate': '0.0005',
          'makerFeeRate': '0.0002',
          'maxLongLeverage': '5',                               <---------------------------
          'maxShortLeverage': '5',                               <---------------------------
          'pricePrecision': '4',
          'quantityPrecision': '0',
          'size': '1',
          'status': '1',
          'symbol': 'STX-USDT',
          'takerFeeRate': '0.0005',
          'tradeMinLimit': '0',
          'tradeMinQuantity': '3',
          'tradeMinUSDT': '2',
          'triggerFeeRate': '0.00045000'},
 'inverse': False,
 'limits': {'amount': {'max': None, 'min': 3.0},
            'cost': {'max': None, 'min': 2.0},
            'leverage': {'max': 5, 'min': None},
            'price': {'max': None, 'min': None}},
 'linear': True,
 'local': {'leverage': 0, 'marginMode': '------', 'positionMode': ''},
 'lowercaseId': None,
 'maker': 0.0002,
 'margin': False,
 'option': False,
 'optionType': None,
 'percentage': True,
 'precision': {'amount': 0,
               'base': None,
               'cost': None,
               'price': 4,
               'quote': None},
 'quote': 'USDT',
 'quoteId': 'USDT',
 'settle': 'USDT',
 'settleId': 'USDT',
 'spot': False,
 'strike': None,
 'subType': 'linear',
 'swap': True,
 'symbol': 'STX/USDT:USDT',
 'taker': 0.0005,
 'type': 'swap'}
```

In other coins (that I have tried) the leverage limits match the ones in the website

```

{'active': True,
 'base': 'BTC',
 'baseId': 'BTC',
 'contract': True,
 'contractSize': 1.0,
 'created': None,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'quote',
 'future': False,
 'id': 'BTC-USDT',
 'index': None,
 'info': {'apiStateClose': 'true',
          'apiStateOpen': 'true',
          'asset': 'BTC',
          'contractId': '100',
          'currency': 'USDT',
          'ensureTrigger': True,
          'feeRate': '0.0005',
          'makerFeeRate': '0.0002',
          'maxLongLeverage': '125',                               <---------------------------
          'maxShortLeverage': '125',                               <---------------------------
          'pricePrecision': '1',
          'quantityPrecision': '4',
          'size': '0.0001',
          'status': '1',
          'symbol': 'BTC-USDT',
          'takerFeeRate': '0.0005',
          'tradeMinLimit': '0',
          'tradeMinQuantity': '0.0001',
          'tradeMinUSDT': '2',
          'triggerFeeRate': '0.00020000'},
 'inverse': False,
 'limits': {'amount': {'max': None, 'min': 0.0001},
            'cost': {'max': None, 'min': 2.0},
            'leverage': {'max': 125, 'min': None},
            'price': {'max': None, 'min': None}},
 'linear': True,
 'local': {'leverage': 0, 'marginMode': '------', 'positionMode': ''},
 'lowercaseId': None,
 'maker': 0.0002,
 'margin': False,
 'option': False,
 'optionType': None,
 'percentage': True,
 'precision': {'amount': 4,
               'base': None,
               'cost': None,
               'price': 1,
               'quote': None},
 'quote': 'USDT',
 'quoteId': 'USDT',
 'settle': 'USDT',
 'settleId': 'USDT',
 'spot': False,
 'strike': None,
 'subType': 'linear',
 'swap': True,
 'symbol': 'BTC/USDT:USDT',
 'taker': 0.0005,
 'type': 'swap'}

```

I'm afraid there's nothing I can do about it. 
I'll report it to the ccxt developers. They can't fix it either, but maybe they can report it to the Bingx developers.

**Comment by germangar** [comment]
Hmm... looks like STX is not the only coin with smaller leverages. XRP has max leverage 10x and Solana max leverage 5x. ETH and BTC however both have 125x. Maybe this is made on purpose. I'll try to ask around.

**Comment by germangar** [comment]
After having the CCXT people asking Bingx developers we figured out the leverage limits defined by Bingx are placeholders, so I added a hack to bypass them by setting them to a minimum of 100x. 
This means in coins like STX whook won't be checking if the leverage is set to the correct limit (50x) and it can be rejected by the server, but you CAN set it now and as long as you pay attention the first time you'll have no problem.

It's up in the repository.

**Comment by iZnogoude** [comment]
@germangar 
thanks a lot, I will test this soon

**Comment by germangar** [comment]
I added a better fix for this. The script will now request the leverage limit from the server at placing the first order. After that it will keep using that one until the script is closed.
